<?php

namespace sonetrin\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use sonetrin\DefaultBundle\Entity\Search;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{

    public function findAllItemsBySearch(Search $search)
    {
        $items = array();
        
        foreach ($search->getResult() as $result)
        {
            $query = $this->createQueryBuilder('i')
                    ->where('i.result = :id')
                    ->setParameter('id', $result->getId())
                    ->getQuery();
            $items[] = $query->getResult();
        }
        return $items;
    }

}
