<?php

namespace sonetrin\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use sonetrin\DefaultBundle\Entity\Search;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ItemRepository extends EntityRepository
{

    public function findAllItemsBySearch(Search $search, $limit = false)
    {
        $results = $search->getResult();
        $items = array();

        foreach ($results as $result)
        {
            $query = $this->createQueryBuilder('r');
            $query->where('r.result = :id');
            $query->setParameter('id', $result->getId());

            if ($limit != false)
            {
                $query->setMaxResults($limit);
            }

            $items = array_merge($items, $query->getQuery()->getResult());
        }
        $array = ($items);

        return $array;
    }

}
