<?php

namespace sonetrin\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KeywordRepository extends EntityRepository
{

    public function findPositiveKeywords()
    {
        $query = $this->createQueryBuilder('k')
            ->where('k.association = :association')
            ->setParameter('association', 'positive')
            ->orderBy('k.expression', 'ASC')
            ->getQuery();
        
        return $query->getResult();
        
    }
    
    public function findNegativeKeywords()      
    {
        $query = $this->createQueryBuilder('k')
            ->where('k.association = :association')
            ->setParameter('association', 'negative')
            ->orderBy('k.expression', 'ASC')
            ->getQuery();

        return $query->getResult();     
     
    }   
}
