<?php

namespace sonetrin\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use sonetrin\DefaultBundle\Entity\Search;

/**
 * KeywordRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ResultRepository extends EntityRepository
{
    public function findRecordsSentiments($searchId)
    {
        $sentiments = array('positive' => 0, 'negative' => 0, 'neutral' => 0);

        $query = $this->createQueryBuilder('r')
                ->where('r.search = :id')
                ->setParameter('id', $searchId)
                ->getQuery();

        $results = $query->getResult();
        foreach ($results as $result)
        {
            foreach ($result->getItem() as $item)
            {
                if ($item->getSentiment() == 'positive')
                {
                    $sentiments['positive']++;
                } 
                elseif ($item->getSentiment() == 'negative')
                {
                    $sentiments['negative']++;
                }
                else
                {
                    $sentiments['neutral']++;
                }
            }
        }
        return $sentiments;
    }
    
}
