sonetrin_default:
    resource: "@sonetrinDefaultBundle/Controller/"
    type:     annotation
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal

login:
    pattern:   /login
    defaults:  { _controller: sonetrinDefaultBundle:Default:login }
    
login_check:
    pattern:   /login_check